server:
  http_port: 8088
  http_doc_port: 8099
  grpc_port: 3033
  name: "simple-go-service"
  env: "local"
external:
  book:
    host: localhost
    port: 3033
    max_retries: 3
    backoff_delays_ms: 100
db:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: secret
    database: example
    max_idle_conns: 10
    max_open_conns: 100
    max_retry: 5
    backoff_delays_ms: 200
jobs:
  simple_example:
    cron_spec: "@every 30s"
    enable: true