server:
  http_port: 8088
  grpc_port: 3033
  name: "simple-go-service"
  env: "local"
db:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: secret
    database: example
    max_idle_conns: 10
    max_open_conns: 100