version: '3.8'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: secret
    ports:
      - ${DB_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
