version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_go_example
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
