version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: secret
    ports:
      - ${DB_PORT}:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
