name: Upload Go test results
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -o app ./cmd

#      - name: Test
#        run: go test -v ./...

      - name: Install dependencies
        run: |
          go install github.com/jstemmer/go-junit-report@latest
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest
          go install github.com/onsi/ginkgo/v2/ginkgo@latest

#      - name: Ginkgo test unit test
#        run: ginkgo -r --focus unit
#
#      - name: Ginkgo test integration test
#        run: ginkgo -r --focus integration

      - name: Ginkgo test
        run: |
          ginkgo --fail-fast -v -cover -coverprofile=coverage.txt -covermode count --junit-report=test-report.xml --keep-separate-reports -r 2>&1
          gocov convert coverage.txt > coverage.json
          gocov-xml < coverage.json > coverage.xml

      - name: Test Reports
        uses: xportation/junit-coverage-report@main
        with:
          junit-path: 'test-report.xml'
          coverage-path: 'coverage.xml'